services:
  - type: web
    name: ultranet-ui
    env: docker
    plan: free
    dockerfilePath: DockerfileUI
    repo: https://github.com/itsarelix/UltraNetFrameworkDemo
    branch: main
    autoDeploy: true
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
    ports:
      - 80

  - type: web
    name: ultranet-api
    env: docker
    plan: free
    dockerfilePath: DockerfileAPI
    repo: https://github.com/itsarelix/UltraNetFrameworkDemo
    branch: main
    autoDeploy: true
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
    ports:
      - 5000