services:
  - type: web
    name: ultranet-ui
    env: docker
    plan: free
    dockerfilePath: ./UltraNet.UI/DockerfileUI
    repo: https://github.com/itsarelix/UltraNetFrameworkDemo
    branch: main
    autoDeploy: true
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production

  - type: web
    name: ultranet-api
    env: docker
    plan: free
    dockerfilePath: ./UltraNet.API/DockerfileAPI
    repo: https://github.com/itsarelix/UltraNetFrameworkDemo
    branch: main
    autoDeploy: true
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production